config/routes.rb
Studyhunter::Application.routes.draw do

  root :to => "locations#index"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :assignments
  resources :students
  resources :project_memberships
  resources :study_sessions
  resources :project_instances
  resources :locations
  resources :comments
  resources :project_classes
  resources :courses
  resources :universities

  match "projects/:id/edit" => "project_classes#edit"
  match "projects/new" => "project_classes#new"
  match "projects/" => "project_classes#index"
  match "projects/:id" => "project_classes#show"

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "registrations#new"
    get "edit_account", :to => "registrations#edit"
    get "my_account", :to => "registrations#show"
  end

end

app/controllers/project_classes_controller.rb
class ProjectClassesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /project_classes
  # GET /project_classes.xml
  def index
    @project_classes = ProjectClass.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @project_classes }
    end
  end

  # GET /project_classes/1
  # GET /project_classes/1.xml
  def show
    @project_class = ProjectClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project_class }
    end
  end

  # GET /project_classes/new
  # GET /project_classes/new.xml
  def new
    initialized_end_date = week_from_now
    @project_class = ProjectClass.new(:end_date => initialized_end_date)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project_class }
    end
  end

  # GET /project_classes/1/edit
  def edit
    @project_class = ProjectClass.find(params[:id])
  end

  # POST /project_classes
  # POST /project_classes.xml
  def create
    params[:project_class][:creator_id] = current_user.id
    @project_class = ProjectClass.new(params[:project_class])

    respond_to do |format|
      if @project_class.save
        format.html { redirect_to(@project_class, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project_class, :status => :created, :location => @project_class }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project_class.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /project_classes/1
  # PUT /project_classes/1.xml
  def update
    @project_class = ProjectClass.find(params[:id])

    respond_to do |format|
      if @project_class.update_attributes(params[:project_class])
        format.html { redirect_to(@project_class, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project_class.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /project_classes/1
  # DELETE /project_classes/1.xml
  def destroy
    @project_class = ProjectClass.find(params[:id])
    @project_class.destroy

    respond_to do |format|
      format.html { redirect_to(project_classes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/project_classes_helper.rb
module ProjectClassesHelper
end

app/views/project_classes/_form.html.erb
<%= form_for(@project_class) do |f| %>
  <% if @project_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_class.errors.count, "error") %> prohibited this project_class from being saved:</h2>

      <ul>
      <% @project_class.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :end_date, "Deadline or Target Date" %> <i>(StudyHunter initializes this date to approximately a week from now.)</i><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_classes/edit.html.erb
<% title "Edit Project Details" %>

<!--<h1>Editing project_class</h1>-->

<%= render 'form' %>

<%= link_to 'Show', @project_class %> |
<%= link_to 'Back', project_classes_path %>

app/views/project_classes/index.html.erb
<% title "All Projects" %>

<table id="list">
  <tr>
    <th>Name</th>
    <th>Creator</th>
    <th>Deadline or Target Date</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @project_classes.each do |project_class| %>
  <tr>
    <td><%= link_to project_class.name, project_class %></td>
    <% creator = User.find project_class.creator_id %>
    <td><%= "#{creator.first_name} #{creator.last_name}" %></td>
    <td><%= project_class.readable_end_date %></td>
    <td><%= project_class.description %></td>
    <td>
      <% if user_signed_in? %>
        <%= link_to "Instantiate!", new_project_instance_path(:project_class_id => project_class.id) %> |
      <% end %>
      <% if ( !project_class.creator.nil? ) %>
        <% if current_user == project_class.creator %>
          <%= link_to 'Edit', edit_project_class_path(project_class) %> |
          <%= link_to 'Remove', project_class, :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<% if user_signed_in? %>
  <a id="user_submit" href="<%= new_project_class_path %>">Create New Project</a>
<% end %>

app/views/project_classes/new.html.erb
<% title "New Project" %>

<!--<h1>New project_class</h1>-->

<%= render 'form' %>

<%= link_to 'Back', project_classes_path %>

app/views/project_classes/show.html.erb
<% title "Project" %>

<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Name:</b>
  <%= @project_class.name %>
</p>

<p>
  <b>Creator:</b>
  <% creator = User.find(@project_class.creator_id) %>
  <%= "#{creator.first_name} #{creator.last_name}" %>
</p>

<p>
  <b>Date created:</b>
  <%= @project_class.readable_created_at %>
</p>

<p>
  <b>Deadline or Target Date:</b>
  <%= @project_class.readable_end_date %>
</p>

<p>
  <b>Description:</b>
  <%= @project_class.description %>
</p>

<% if ( !@project_class.creator.nil? ) %>
  <% if current_user == @project_class.creator %>
    <%= link_to 'Edit', edit_project_class_path(@project_class) %> |
  <% end %>
<% end %>
<%= link_to 'Back', project_classes_path %>