config/routes.rb
Studyhunter::Application.routes.draw do

  root :to => "locations#index"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :assignments
  resources :students
  resources :project_memberships
  resources :study_sessions
  resources :project_instances
  resources :locations
  resources :comments
  resources :project_classes
  resources :courses
  resources :universities

  match "projects/:id/edit" => "project_classes#edit"
  match "projects/new" => "project_classes#new"
  match "projects/" => "project_classes#index"
  match "projects/:id" => "project_classes#show"

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "registrations#new"
    get "edit_account", :to => "registrations#edit"
    get "my_account", :to => "registrations#show"
  end

end

app/models/study_session.rb
class StudySession < ActiveRecord::Base
  belongs_to :project_instance
  belongs_to :location
end

app/controllers/study_sessions_controller.rb
class StudySessionsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /study_sessions
  # GET /study_sessions.xml
  def index
    @study_sessions = StudySession.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @study_sessions }
    end
  end

  # GET /study_sessions/1
  # GET /study_sessions/1.xml
  def show
    @study_session = StudySession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @study_session }
    end
  end

  # GET /study_sessions/new
  # GET /study_sessions/new.xml
  def new
    @study_session = StudySession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @study_session }
    end
  end

  # GET /study_sessions/1/edit
  def edit
    @study_session = StudySession.find(params[:id])
  end

  # POST /study_sessions
  # POST /study_sessions.xml
  def create
    @study_session = StudySession.new(params[:study_session])

    respond_to do |format|
      if @study_session.save
        format.html { redirect_to(@study_session, :notice => 'Study session was successfully created.') }
        format.xml  { render :xml => @study_session, :status => :created, :location => @study_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @study_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /study_sessions/1
  # PUT /study_sessions/1.xml
  def update
    @study_session = StudySession.find(params[:id])

    respond_to do |format|
      if @study_session.update_attributes(params[:study_session])
        format.html { redirect_to(@study_session, :notice => 'Study session was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @study_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /study_sessions/1
  # DELETE /study_sessions/1.xml
  def destroy
    @study_session = StudySession.find(params[:id])
    @study_session.destroy

    respond_to do |format|
      format.html { redirect_to(study_sessions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/study_sessions_helper.rb
module StudySessionsHelper
end

app/views/study_sessions/_form.html.erb
<%= form_for(@study_session) do |f| %>
  <% if @study_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_session.errors.count, "error") %> prohibited this study_session from being saved:</h2>

      <ul>
      <% @study_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_instance_id %><br />
    <%= f.text_field :project_instance_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :meeting_date %><br />
    <%= f.datetime_select :meeting_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/study_sessions/edit.html.erb
<% title "Edit Study Session" %>

<!--<h1>Editing study_session</h1>-->

<%= render 'form' %>

<%= link_to 'Show', @study_session %> |
<%= link_to 'Back', study_sessions_path %>

app/views/study_sessions/index.html.erb
<% title "Study Sessions" %>

<!--<h1>Listing study_sessions</h1>-->

<table>
  <tr>
    <th>Project instance</th>
    <th>Location</th>
    <th>Meeting date</th>
    <th></th>
  </tr>

<% @study_sessions.each do |study_session| %>
  <tr>
    <td><%= study_session.project_instance_id %></td>
    <td><%= study_session.location_id %></td>
    <td><%= study_session.meeting_date %></td>
    <td>
      <%= link_to 'Show', study_session %>
      <% if ( !study_session.project_instance.nil? and !study_session.project_instance.users.nil? ) %>
        <% if study_session.project_instance.users.includes?(current_user) %>
          <%= link_to 'Edit', edit_study_session_path(study_session) %>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<% if user_signed_in? %>
  <%= link_to 'New Study session', new_study_session_path %>
<% end %>

app/views/study_sessions/new.html.erb
<% title "New Study Session" %>

<!--<h1>New study_session</h1>-->

<%= render 'form' %>

<%= link_to 'Back', study_sessions_path %>

app/views/study_sessions/show.html.erb
<% title "Study Session" %>

<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Project instance:</b>
  <%= @study_session.project_instance_id %>
</p>

<p>
  <b>Location:</b>
  <%= @study_session.location_id %>
</p>

<p>
  <b>Meeting date:</b>
  <%= @study_session.meeting_date %>
</p>


<% if ( !@study_session.project_instance.nil? and !@study_session.project_instance.users.nil? ) %>
  <% if @study_session.project_instance.users.includes?(current_user) %>
    <%= link_to 'Edit', edit_study_session_path(@study_session) %> |
  <% end %>
<% end %>
<%= link_to 'Back', study_sessions_path %>