config/routes.rb
Studyhunter::Application.routes.draw do

  root :to => "locations#index"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :assignments
  resources :students
  resources :project_memberships
  resources :study_sessions
  resources :project_instances
  resources :locations
  resources :comments
  resources :project_classes
  resources :courses
  resources :universities

  match "projects/:id/edit" => "project_classes#edit"
  match "projects/new" => "project_classes#new"
  match "projects/" => "project_classes#index"
  match "projects/:id" => "project_classes#show"

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "registrations#new"
    get "edit_account", :to => "registrations#edit"
    get "my_account", :to => "registrations#show"
  end

end

app/models/project_instance.rb
class ProjectInstance < ActiveRecord::Base
  has_many :project_memberships, :dependent => :destroy
  has_many :users, :through => :project_memberships

  has_many :study_sessions, :dependent => :destroy
  has_many :locations, :through => :study_sessions

  belongs_to :project_class
  has_many :comments, :dependent => :destroy

  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"

  validates :project_class_id, :owner_id, :presence => true

  def readable_end_date
    end_date.strftime("%b %e - %I:%M %p")
  end

  def readable_created_at
    created_at.strftime("%b %e - %I:%M %p")
    end

  def readable_updated_at
    updated_at.strftime("%b %e - %I:%M %p")
  end
end

app/controllers/project_instances_controller.rb
class ProjectInstancesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /project_instances
  # GET /project_instances.xml
  def index
    @project_instances = ProjectInstance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @project_instances }
    end
  end

  # GET /project_instances/1
  # GET /project_instances/1.xml
  def show
    @project_instance = ProjectInstance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project_instance }
    end
  end

  # GET /project_instances/new
  # GET /project_instances/new.xml
  def new
    if !params[:project_class_id].nil?
      @project_instance = ProjectInstance.new

      # Build and initialize project_class association.
      @project_instance.build_project_class
      project_class = ProjectClass.find params[:project_class_id]
      @project_instance.project_class = project_class

      # Get default attributes from the project_class.
      inherited_attributes = { :name => project_class.name, :description => project_class.description  }
      inherited_attributes[:end_date] = project_class.end_date unless project_class.end_date.nil?
      @project_instance.attributes = inherited_attributes

      flash.now[:notice] = "The fields have been prepopulated for you.
                           Feel free to edit the details for your particular instance."
    else
      initialized_end_date = week_from_now
      @project_instance = ProjectInstance.new(:end_date => initialized_end_date)
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project_instance }
    end
  end

  # GET /project_instances/1/edit
  def edit
    @project_instance = ProjectInstance.find(params[:id])
  end

  # POST /project_instances
  # POST /project_instances.xml
  def create
    params[:project_instance][:owner_id] = current_user.id
    @project_instance = ProjectInstance.new(params[:project_instance])

    respond_to do |format|
      if @project_instance.save
        format.html { redirect_to(@project_instance, :notice => 'Project instance was successfully created.') }
        format.xml  { render :xml => @project_instance, :status => :created, :location => @project_instance }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project_instance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /project_instances/1
  # PUT /project_instances/1.xml
  def update
    @project_instance = ProjectInstance.find(params[:id])

    respond_to do |format|
      if @project_instance.update_attributes(params[:project_instance])
        format.html { redirect_to(@project_instance, :notice => 'Project instance was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project_instance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /project_instances/1
  # DELETE /project_instances/1.xml
  def destroy
    @project_instance = ProjectInstance.find(params[:id])
    @project_instance.destroy

    respond_to do |format|
      format.html { redirect_to(project_instances_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/project_instances_helper.rb
module ProjectInstancesHelper
end

app/views/project_instances/_form.html.erb
<%= form_for(@project_instance) do |f| %>
  <% if @project_instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_instance.errors.count, "error") %> prohibited this project_instance from being saved:</h2>

      <ul>
      <% @project_instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project_class_id %><br />
    <%= f.text_field :project_class_id %>
  </div>
  <div class="field">
    <%= f.label :end_date, "Deadline or Target Date" %>  <br/>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_instances/edit.html.erb
<% title "Edit Project" %>

<!--<h1>Editing project_instance</h1>-->

<%= render 'form' %>

<%= link_to 'Show', @project_instance %> |
<%= link_to 'Back', project_instances_path %>

app/views/project_instances/index.html.erb
<% title "Project Instances" %>

<!--<h1>Listing project_instances</h1>-->

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>Instantiated</th>
    <th>Last modified</th>
    <th>Project class</th>
    <th>Description</th>
    <th>Deadline or Target Date</th>
    <th></th>
  </tr>

<% @project_instances.each do |project_instance| %>
  <tr>
    <td><%= link_to project_instance.name, project_instance %></td>
    <td><%= "#{project_instance.owner.first_name} #{project_instance.owner.last_name}" unless project_instance.owner.nil? %></td>
    <td><%= project_instance.readable_created_at %></td>
    <td><%= project_instance.readable_updated_at %></td>
    <td><%= project_instance.project_class.nil? ? "" : link_to(project_instance.project_class.name, project_instance.project_class ) %></td>
    <td><%= project_instance.description %></td>
    <td><%= project_instance.readable_end_date if !project_instance.end_date.nil? %></td>
    <td>
      <% if user_signed_in? %>
        <%= link_to "Join!", project_memberships_path %> |
      <% end %>
      <% if ( !project_instance.owner.nil? ) %>
        <% if current_user == project_instance.owner %>
          <%= link_to 'Edit', edit_project_instance_path(project_instance) %> |
          <%= link_to 'Remove', project_instance, :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<% if user_signed_in? %>
  <%= link_to 'New Project Instance', new_project_instance_path %>
<% end %>

app/views/project_instances/new.html.erb
<% title "New Project Instance" %>

<!--<h1>New project_instance</h1>-->

<%= render 'form' %>

<%= link_to 'Back', project_instances_path %>

app/views/project_instances/show.html.erb
<% title "Project Instance" %>

<!--<p id="notice"><%#= notice %></p>-->

<p>
  <b>Name:</b>
  <%= @project_instance.name %>
</p>

<p>
  <b>Owner:</b>
  <%= "#{@project_instance.owner.first_name} #{@project_instance.owner.last_name}" unless @project_instance.owner.nil? %>
</p>

<p>
  <b>Instantiated:</b>
  <%= @project_instance.readable_created_at %>
</p>

<p>
  <b>Last modified:</b>
  <%= @project_instance.readable_updated_at %>
</p>

<p>
  <b>Project class:</b>
  <%= @project_instance.project_class.name unless @project_instance.project_class.nil? %>
</p>

<p>
  <b>Description:</b>
  <%= @project_instance.description %>
</p>

<p>
  <b>Deadline or Target Date:</b>
  <%= @project_instance.readable_end_date if !@project_instance.end_date.nil? %>
</p>


<% if ( !@project_instance.owner.nil? ) %>
  <% if current_user == @project_instance.owner %>
    <%= link_to 'Edit', edit_project_instance_path(@project_instance) %> |
  <% end %>
<% end %>
<%= link_to 'Back', project_instances_path %>

<p>
  <h3 id="comments_count"><%= pluralize(@project_instance.comments.size, "Comment") %></h3>
</p>

<div id="comments">
  <%= render @project_instance.comments %>
</div>

<h4>Add a Comment:</h4>
<%= form_for Comment.new(:project_instance => @project_instance) do |f| %>
  <%= f.hidden_field :project_instance_id %>
  <%= f.hidden_field :author_id, :value => current_user.id %>
  <p>
    <%= f.text_area :body, :rows => 4 %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
<% end %>